### ISSUE TITLE
Definir tema e escopo do projeto

### ISSUE THREAD

**Issue by guiaugusto** [deeplearningunb/doggdex#1]
**Descrição**

Esta _issue_ tem como objetivo definir o tema para o projeto final da disciplina, assim como o escopo geral da proposta a ser apresentada.

**Tarefas**

- [x] Especificar tema a ser trabalhado
- [x] Encontrar _dataset_ para o tema apresentado

**Comment by andre-filho** [comment]
https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

**Comment by andre-filho** [comment]
https://www.kaggle.com/c/dog-breed-identification/overview

**Comment by andre-filho** [comment]
Reconhecimento da raça de um dogginho a partir de imagem
