### ISSUE TITLE
Avaliação

### ISSUE THREAD

**Issue by diegodorgam** [deeplearningunb/doggdex#4]
A avaliação é baseada nos 5 seguintes critérios objetivos booleanos: 

1. Proposta
A proposta do projeto é relevante para uma comunidade, em sentido que, a aplicação dessas tecnologias podem trazer algum diferencial positivo para a comunidade que serve.

2. Apresentação
Julga o preparo do arquivo README.md para apresentar o problema, o raciocínio e a solução apresentada pelo projeto, assim como possíveis comparações com outras soluções.

3. Organização
Criação das issues para demonstrar as tarefas, bugs e novas features do projeto, de forma a deixar aberto e claro para a comunidade quais são os desafios do projeto e como ela pode contribuir.

4. Roadmap
Demonstrar por meio de milestones de versões do projeto, como está programada a evolução da solução.

5. Tecnica
Aplicação objetiva dos conhecimentos adquiridos em sala de aula.  

| Proposta | Apresentação | Organização | Roadmap | Tecnica |
|:-:|:-:|:-:|:-:|:-:|
| 1 | 1 | 1 | 0 | 1 |
| ok | precisa terminar o README | ok | não encontrei Roadmap.md ou Milestones, ou issues | ok |

**Comment by guiaugusto** [comment]
Opa @diegodorgam, acho que essa avaliação se refere à outro grupo. Nossa proposta é criar uma rede neural que identifica raças de cães através de reconhecimento de imagem, diferente um pouco do tema mencionado no início da issue.

**Comment by diegodorgam** [comment]
perdão @guiaugusto, o comentário veio de um copia e cola, removi já, a avaliação que conta é o quadro final.

**Comment by guiaugusto** [comment]
Acredito que as pendências para a primeira versão proposta estão finalizadas.

A respeito das milestones e roadmap, orientamos em 3 milestones simples, a primeira sugerindo como a de decisão, onde decidimos o tema do projeto e encontramos o dataset. Já, a segunda, foi a sprint de desenvolvimento da primeira versão, onde testamos a construção dos algoritmos com diversos modelos até chegarmos no InceptionResNetV2, que finalizamos o projeto com ele. Por fim, a terceira sprint foi para retoques finais do projeto, como pendências para a primeira versão da aplicação.

A respeito do roadmap inicial, nós fizemos um simples, com as propostas que tinhamos pensado inicialmente para a versão final da aplicação. Ela se encontra no arquivo [ROADMAP.md](https://github.com/deeplearningunb/doggdex/blob/master/docs/ROADMAP.md)

**Comment by diegodorgam** [comment]
Show, notas atualizadas, parabéns!
